config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :users
  end

  devise_for(:user)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ispost_user , only: [:edit,:update,:destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    puts @post.user
  end

  # GET /posts/newPost was successfully created.
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Le post a été créé' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Le post a été modifié' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Le post a été supprimé' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text,:image)
    end

    def ispost_user
      if current_user != @post.user
         redirect_to posts_url, notice: 'Vous n\'avez pas le droit car vous ne l\'avez pas crée'
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <%= form_with(model: post, local: true) do |form| %>
        <% if post.errors.any? %>
          <div class="row">
            <div id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
            <% post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
          </div>
        <% end %>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix ">subject</i>
            <%= form.label :title %><br />
            <%= form.text_field :title, autocomplete: "off" %>
          </div>
          <div class="input-field col s12">
            <i class="material-icons prefix ">assignment</i>
            <%= form.label :text %><br />
            <%= form.text_area :text, autocomplete: "off" , :class=>"materialize-textarea" %>
          </div>
          <div class="input-field col s12">
            <i class="material-icons prefix pt-5">attach_file</i>
            <%= form.file_field :image, autocomplete: "off" %>
          </div>
        </div>
        <div class="row">
          <div class="col s12">
            <div class="center">
              <%= form.submit "Enregistrer", :class => "btn waves-effect waves-light green margin-top" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div class="center">
        <h4>Editer Post</h4>
      </div>
    </div>
  </div>
</div>

<%= render 'form', post: @post %>

<%= link_to 'Voir', @post ,:class=>"btn-floating btn-large waves-effect waves-light red btn-view-post" %>

<%= link_to '<=', posts_path ,:class=>"btn-floating btn-large waves-effect waves-light red btn-back-post" %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div class="center">
        <h4>Posts</h4>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col s4">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <a href="#">
            <img src="<%= post.image %>" alt="item-img" height="170">
          </a>
          <h4 class="card-title text-shadow m-0"><%= post.title %></h4>
        </div>
        <div class="card-action-buttons margin-top">
          <div class="row padding-left padding-right">
            <div class="col s12 center  ">
              <%= link_to "Details",  post_path(post), :class => "waves-effect waves-light btn orange" %>
            </div>
          </div>
        </div>
        <div class="card-content no-padding ">
          <div class="padding-left">
            <p class="row mb-1">
              <small class="left"><%= post.created_at %></small>
            </p>
            <p class="item-post-content">  <%= post.text %></p>
          </div>
          <div class="row ">
            <div class="chip right ">
              <%= link_to post.user.email, post_user_path(post, post.user) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<%= link_to '+', new_post_path ,:class=>"btn-floating btn-large waves-effect waves-light red btn-add-post" %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div class="center">
        <h4>Nouvau Post</h4>
      </div>
    </div>
  </div>
</div>
<%= render 'form', post: @post %>

<%= link_to '<=', posts_path ,:class=>"btn-floating btn-large waves-effect waves-light red btn-back-post" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div class="center">
        <h4>Detail Post </h4>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s5 ">
    <div class="row">
      <div class="col s12">
        <div class="card-panel ">
          <div class="center">
            <h6>Image </h6>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <div class="card-panel">
          <div class="card-image waves-effect waves-block waves-light center">
            <img src="<%= @post.image %>" alt="item-img">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col s5 offset-s2">
    <div class="row">
      <div class="col s12">
        <div class="card-panel">
          <div class="center">
            <h6>Titre : </h6>
            <%= @post.title%>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <div class="card-panel">
          <div class="center">
            <h6>Chapeau : </h6>
            <%= @post.text %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <div class="card-panel">
          <div class="center">
            <h6>Crée le : </h6>
            <%= @post.created_at %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <div class="card-panel">
          <div class="center">
            <h6>Crée par: </h6>
            <%= link_to @post.user.email, post_user_path(@post, @post.user) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<% if current_user == @post.user %>
  <%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Etes vous sur de vouloir supprimer ce post ?"}, :class => "waves-effect waves-light btn red btn-remove-post" %>



  <%= link_to 'Edit', edit_post_path(@post) ,:class=>"btn-floating btn-large waves-effect waves-light red btn-view-post" %>
<% end %>



<%= link_to '<=', posts_path ,:class=>"btn-floating btn-large waves-effect waves-light red btn-back-post" %>